# @package _global_
defaults:
  - default
  - _self_

data:

  num_classes: 16

  source:
    dataset: 'synthia'
    kwargs:
      root: ${root}/datasets/SYNTHIA/RAND_CITYSCAPES
      list_path: ${root}/datasets/synthia_list
      class_16: True

  target:
    kwargs:
      class_16: True

model:
  backbone: deeplabv2_multi
  checkpoint: null
